### ISSUE TITLE
Additional way of representing uknown tags

### ISSUE THREAD

**Issue by ivan-kleshnin** [alexmingoia/jsx-transform#14]
Given unknown tag:

```
<HelloWorld/>
```

With JSX constructor `h`, it currently can be transformed to:

```
h(HelloWorld, null);
```

or

```
h.HelloWorld(null);
```

Additional (fairly logical) transformation can be 
```
h('HelloWorld', null);
```

It's required for libs that make some sort of global registration on their own.
See https://github.com/staltz/cycle/issues/35

Would you mind adding one more flag (or updating existing) to handle this case?

**Comment by alexmingoia** [comment]
Yes this would be nice to have. It should be included when jsx-transform is rewritten for es6 support.

**Comment by alexmingoia** [comment]
```javascript
var transformed = jsx.transformFile('index.jsx', {
  docblockUnknownTags: true
  unknownTagsAsString: true
});
```
