### ISSUE TITLE
Custom attributes 

### ISSUE THREAD

**Issue by ivan-kleshnin** [alexmingoia/jsx-transform#15]
Please check this https://github.com/Matt-Esch/virtual-dom/blob/7cd99a160f8d7c9953e71e0b26a740dae40e55fc/docs/vnode.md#custom-attributes-data-

Quoting docs:
> var doThis = new VNode('div', { attributes: { "data-example": "I will render" }})
var notThis = new VNode('div', { "data-example": "I will not render" })

So all `data-*` attributes should go under `{attributes: ...}` namespace.

**jsx-transform** renders this in second (wrong) way:

```html
<li data-index={i} class={makeClass({active: active == i})}>{item}</li>
```
```javascript
h('li', {'data-index': i, className: makeClass({active: active == i})}, [item])
```

Should be:

```javascript
h('li', {attributes: {'data-index': i}, className: makeClass({active: active == i})}, [item])
```

**Comment by alexmingoia** [comment]
jsx-transform simply desugars JSX into JS. It knows nothing about the code.

```javascript
h('li', {attributes: {'data-index': i}, className: makeClass({active: active == i})}, [item])
```

The corresponding JSX for the above:

```javascript
<li attributes={{'data-index': i}} class={makeClass({active: active == i})}>{item}</li>
```

**Comment by alexmingoia** [comment]
It should be `h()` that puts data-* properties into attributes, not jsx-transform.

**Comment by ivan-kleshnin** [comment]
Ah, ok. I ended up with the same solution but considered it a workaround. 
But that's really virtual dom specific stuff, I agree.
