### ISSUE TITLE
JSX Spread Attributes

### ISSUE THREAD

**Issue by markuskobler** [alexmingoia/jsx-transform#19]
Has anyone had any thoughts on adding support for [JSX Spread Attributes](https://facebook.github.io/react/docs/jsx-spread.html)?

```javascript
var component = <Component {...props} />;
```

Currently the jstransform has no problems parsing the expression but jsx-transform blows up on [this line](https://github.com/alexmingoia/jsx-transform/blob/v0.12.1/lib/visitor.js#L83) because it always expects attributes to have a name.

Fixing should be simple enough with the exception of deciding how best to solve the equivalent of React's `spread` function which is uses when it desugars the jsx code.

```javascript
React.createElement(Overview, React.__spread({},  state.articles, {foo: "bar"})),
```

Personally I should be possible to specify a global function that provides spread support and fallback to [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) if not defined.
I'm just worried that if it's not a modern browser it will subtly break peoples code.

Any thoughts?

**Comment by alexmingoia** [comment]
Even Object.assign isn't widely supported by modern browsers. However, I don't think browser support is an issue because as long as you don't use spread notation in your JSX you won't ever run into the issue.

**Comment by markuskobler** [comment]
Thanks!

**Comment by alexmingoia** [comment]
No problem. Beware I changed the API around a bit, including option names, and deprecated a bunch of options. It's all in the docs and changelog.
