### ISSUE TITLE
Why docblocks support has been removed?

### ISSUE THREAD

**Issue by kuraga** [alexmingoia/jsx-transform#20]
Why docblocks support has been removed?

**Comment by alexmingoia** [comment]
React removed support for it. It was removed from Facebook's [JSX standard](https://facebook.github.io/jsx/). It's redundant with the transform options. If you don't want to use the transform on certain files, don't run it through the transform in the first place. Also, it should be safe to run the transform on JS that doesn't have any JSX. If you want to separate JSX files use the `.jsx` extension and separate them that way.

**Comment by kuraga** [comment]
Thanks.
