### ISSUE TITLE
passing optional arguments to Vnode

### ISSUE THREAD

**Issue by timuric** [alexmingoia/jsx-transform#29]
Sorry if this is a wrong place to ask this question :) 
Virtual dom has optional arguments such as Key or Namespace https://github.com/Matt-Esch/virtual-dom/blob/7cd99a160f8d7c9953e71e0b26a740dae40e55fc/docs/vnode.md#arguments
The key argument is very useful when you want efficiently reorder lists. Is there a way to define key argument in jsx syntax?

**Comment by alexmingoia** [comment]
While it might be useful, I don't want to couple jsx-transform to virtual-dom. The best place for this would be in your vnode factory which should look for a "key" property and use it as an argument to the vnode.

```javascript
var h = require('virtual-dom/h');
var jsx = require('jsx-transform');

function DOM(tagName, props, children) {
  var key;

  if (props.key) {
    key = props.key;
  }

  return h(tagName, props, children, key);
}

var js = jsx.fromFile('./app.jsx', {
  factory: 'DOM'
});
```

**Comment by alexmingoia** [comment]
Actually.. that's not necessary if you use `virtual-dom/h` (virtual-hyperscript). See: https://github.com/Matt-Esch/virtual-dom/blob/7cd99a160f8d7c9953e71e0b26a740dae40e55fc/virtual-hyperscript/index.js#L31-L35

**Comment by timuric** [comment]
@alexmingoia Thank you very much for all the examples!
