### ISSUE TITLE
esprima-fb error when using default parameter value and destructuring

### ISSUE THREAD

**Issue by cedeber** [alexmingoia/jsx-transform#40]
Hi. If you do:

``` js
function main ( { x = 5, y = 3 } = {} ) {
    ..
}
```

and compile it thanks to Babel and browserify you've got the error
`Unexpected token = while parsing file`

It works well without jsx-transform. As esprima-fb is not maintained, does it exist a solution to replace it? (Esprima looks like to support JSX now)
Thanks.

**Comment by cedriceberhardt** [comment]
More infos #https://github.com/jquery/esprima/issues/1467

**Comment by wildlyinaccurate** [comment]
jsx-transform uses jstransform (another unmaintained Facebook project) to do the actual transformation, so unfortunately it's not as simple as swapping esprima-fb for esprima@3.x.x.

I will try and set aside some time to investigate moving away from jstransform and esprima-fb but I think it might require a significant rewrite.

**Comment by cedriceberhardt** [comment]
Ok, I understand. I will study a bit how jsx-transform work and see what I can do too.
