### ISSUE TITLE
Namespace attributes are not supported

### ISSUE THREAD

**Issue by vstanyshevskyy** [alexmingoia/jsx-transform#44]
It is not possible to use svg tags in jsx with jsx-transform.
For example:
`<svg><use xlink:href="#icon-star-filled"></use></svg>`
I can see in the code this:
`if (attr.name.namespace) {
      throw new Error(
        'Namespace attributes not supported. JSX is not XML.'
      );
    }`
But namespace attributes are valid according to JSX specs](https://facebook.github.io/jsx/)

**Comment by DanielRuf** [comment]
Bump. I also have this issue. So where is the full implementation of the spec which is not opiniated?

**Comment by dfcreative** [comment]
@alexmingoia @wildlyinaccurate @kuraga is it possible to bypass this check? I am using jsx for svg datavis with [virtual-hyperscript-svg](https://github.com/substack/virtual-hyperscript-svg) and that is total bummer.

I can do a PR if you need.
Thanks!

**Comment by wildlyinaccurate** [comment]
This is @alexmingoia's project so I don't want to step on his toes, but I would be in favour of accepting a PR that adds support for namespaces.

**Comment by dfcreative** [comment]
@wildlyinaccurate the PR is #45, please take a look :)
