### ISSUE TITLE
es6 features option /  provide visitors array

### ISSUE THREAD

**Issue by jtangelder** [alexmingoia/jsx-transform#6]
Like the jsx-loader plugin (https://github.com/petehunt/jsx-loader), this might be useful. It might be a bit out of scope of the project, but a nice addition. Adding support for es6 with a separate loader could be done, but it has to parse the source again, and that is inefficient.

Let me know if you would like this in this project, i'm willing to write a PR for this...!

**Comment by jtangelder** [comment]
Source-code; https://github.com/facebook/react/blob/master/vendor/fbtransform/visitors.js

**Comment by alexmingoia** [comment]
Yeah, sounds good. :+1:

**Comment by jtangelder** [comment]
Great! Guess that exposing the visitor is the most flexible option anyway :-)

https://github.com/alexmingoia/jsx-transform/pull/7
